<?php

/**
 * @file
 * Responsive image compatibility for the Pinterest hover button.
 */

use Drupal\responsive_image\Entity\ResponsiveImageStyle;

/**
 * Implements hook_preprocess_responsive_image.
 */
function pinterest_responsive_preprocess_responsive_image(&$variables) {
  if (empty($variables['img_element']['#uri'])) {
    if (is_array($variables['img_element']['#srcset'])
      && count($variables['img_element']['#srcset']) == 1) {
      // When there is only one choice for srcset, use it. By default, this is
      // the fallback image, which seems fine.
      $variables['img_element']['#attributes']['data-pin-media'] = $variables['img_element']['#srcset'][0]['uri'];
    } else {
      // Locate and use the fallback image the hard way.
      $responsive_image_style = ResponsiveImageStyle::load($variables['responsive_image_style_id']);

      if ($responsive_image_style) {
        $image = \Drupal::service('image.factory')->get($variables['uri']);
        $variables['img_element']['#attributes']['data-pin-media'] = _responsive_image_image_style_url($responsive_image_style->getFallbackImageStyle(), $image->getSource());
      }
    }
  }
}
