pinterest_hover.settings:
  type: mapping
  label: 'Pinterst hover module settings'
  mapping:
    load_pinterest_js:
      type: boolean
      label: "Whether this module should add a script tag to all pages loading Pinterest's JavaScript and enabling hover buttons. You may want to turn this off if you include the Pinterest JavaScript through another module or theme."
    exclude_hover_selectors:
      type: string
      label: 'CSS selectors matching images that should not be pinnable or have Pin It hover buttons. One selector per line.'
